name: MirandaCorcoran
favicon: null
layout_spectrum: 0.50391
typography_spectrum: 0.32746
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d2d2d0'
    - '#ababab'
    - '#282826'
    - '#5a5a5a'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
