name: MirandaCorcoran
favicon: null
layout_spectrum: 0.74802
typography_spectrum: 0.53063
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2d2d2d'
    - '#ffffff'
    - '#616161'
    - '#b0b0b0'
    - '#888888'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
